name: ci

on:
  push:

    tags:
      - '*'
  pull_request:
    branches: [ "main" ]

jobs:
  my_build_job:
    runs-on: ubuntu-latest

    steps:
      - name: Проверка кода
        uses: actions/checkout@v4

      - name: Вход на Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.USER_DOCKER_HUB }}
          password: ${{ secrets.TOKEN_DOCKER_HUB }}

      - name: Сборка Docker-образа
        env:
          IMAGE_TAG: ${{ github.ref_type == 'tag' && github.ref_name || github.sha }}
        run: |
          docker build . --file Dockerfile --tag nginx:$IMAGE_TAG
          docker tag nginx:latest ${{ secrets.USER_DOCKER_HUB }}/nginx:$IMAGE_TAG
          
      - name: Push Docker-образа в Docker Hub
        run: |        
          docker push ${{ secrets.USER_DOCKER_HUB }}/nginx:$IMAGE_TAG
          docker push ${{ secrets.USER_DOCKER_HUB }}/nginx:latest
          
