         
name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    tags:
      - '*'
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Проверка кода
        uses: actions/checkout@v4

      - name: Вход на Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.USER_DOCKER_HUB }}
          password: ${{ secrets.TOKEN_DOCKER_HUB }}

      - name: Build, tag, and push image to Yandex Cloud Container Registry
        env:
          CR_REGISTRY: crpd8j7bbfi9io9g9qdt
          CR_REPOSITORY: clock-app
          IMAGE_TAG: ${{ github.ref_type == 'tag' && github.ref_name || github.sha }}
        run: |
          docker build -t ${{ secrets.USER_DOCKER_HUB }}:$IMAGE_TAG -t nginx:latest .
          docker push ${{ secrets.USER_DOCKER_HUB }}:$IMAGE_TAG
          docker push ${{ secrets.USER_DOCKER_HUB }}:latest
